var listenArr = [
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"57","channelName":"BBC 2","videoUrl":"https://bozztv.com/36bay2/gin/giniko_bbctwo_1000kb_36bay2/index.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"64","channelName":"GEM TV","videoUrl":"http://210.210.155.66/h/h19/01.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"66","channelName":"Hits Movies","videoUrl":"http://103.22.183.136:8081/live/hits-movies/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"70","channelName":"malaytv1","videoUrl":"https://rtm1mobile.secureswiftcontent.com/Origin01/ngrp:RTM1/chunklist_b3696000.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"61","channelName":"eGG Network","videoUrl":"http://210.210.155.66/h/h22/01.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"55","channelName":"222","videoUrl":"https://astro3.rastream.com/melodyTV1"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"68","channelName":"K+","videoUrl":"http://210.210.155.66/h/h08/01.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"65","channelName":"HITS","videoUrl":"http://210.210.155.66/h/h37/01.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"33","channelName":"Thainbt","videoUrl":"http://live.prd.go.th:1935/live/ch1_L.sdp/chunklist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"31","channelName":"SEATV","videoUrl":"http://203.189.147.211:1935/live/mp4:myStream_720p/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"42","channelName":"வசந்தம்","videoUrl":"https://d39v9xz8f7n8tk.cloudfront.net/hls/vsnthmctv/master02.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"54","channelName":"新传媒朝阳频道Suria马来语","videoUrl":"https://d11h6a6nhl9kj9.cloudfront.net/hls/suriactv/master02.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"18","channelName":"Malaynews","videoUrl":"https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_3.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"69","channelName":"KIX","videoUrl":"http://210.210.155.66/h/h07/01.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"7","channelName":"AstroAwani","videoUrl":"https://bcsecurelivehls-i.akamaihd.net/hls/live/722763/4508222217001/stream01/streamPlaylist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"39","channelName":"TVIKIM","videoUrl":"http://edge.vediostream.com:80/abr/tvikim/live/tvikim_source/chunks.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"26","channelName":"NTV7","videoUrl":"https://raw.githubusercontent.com/exodiver/IPTV/master/M3U8/Token/NTV7.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"56","channelName":"AXN","videoUrl":"http://210.210.155.66/h/h141/02.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"63","channelName":"Food Food","videoUrl":"https://sonyent.pc.cdn.bitgravity.com/sonyent/live/food_food.smil/chunklist_b1300000.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"43","channelName":"八度空间","videoUrl":"https://raw.githubusercontent.com/exodiver/IPTV/master/M3U8/Token/8TV.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"28","channelName":"ONE-HD","videoUrl":"http://live.pjmcdn.info/live/ONE-HD.stream/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"53","channelName":"新加坡新传媒8频道","videoUrl":"https://d34e90s3s13i7n.cloudfront.net/hls/ch8ctv/master02.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"11","channelName":"Channel 5","videoUrl":"https://dlau142f16b92.cloudfront.net/hls/ch5ctv/master02.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"22","channelName":"MiamiTV-JennyLive(18+)","videoUrl":"http://23.111.128.190:1935/miamitv/smil:miamitvROKU/chunklist_b2592000.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"24","channelName":"New-TV","videoUrl":"http://live.pjmcdn.info/live/New-TV.stream/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"12","channelName":"Channel NewsAsia","videoUrl":"https://d2e1asnsl7br7b.cloudfront.net/7782e205e72f43aeb4a48ec97f66ebbe/index_5.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"46","channelName":"妙米","videoUrl":"https://d3kw4vhbdpgtqk.cloudfront.net/hls/miaomipcweb/04.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"60","channelName":"DABL","videoUrl":"https://cbsta49f-dabl68fc.global.ssl.fastly.net/out/v1/dfecb53fbf434b6bbbfd91d8a2549381/manifest_24.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"38","channelName":"TV9","videoUrl":"https://raw.githubusercontent.com/exodiver/IPTV/master/M3U8/Token/TV9.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"34","channelName":"The Works","videoUrl":"https://mgm-ssai.akamaized.net/amagi_hls_data_mgmAAAAAA-theworks/CDN/720x404_1425600/index.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"15","channelName":"Docurama","videoUrl":"https://cinedigm.vo.llnwd.net/conssui/amagi_hls_data_xumo1234A-docuramaA/CDN/1920x1080_4528000/chunklist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"29","channelName":"Radio51","videoUrl":"http://59d7d6f47d7fc.streamlock.net/canale51/canale51/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"32","channelName":"TF1 Séries Films","videoUrl":"https://tsf-hls-live-ssl.tf1.fr/tsf/1/hls/live_2328.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"20","channelName":"MCOT-HD","videoUrl":"http://live.pjmcdn.info/live/MCOT-HD.stream/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"23","channelName":"mono29","videoUrl":"http://live.pjmcdn.info/live/mono29.stream/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"40","channelName":"U频道","videoUrl":"https://d3inlz9elsutjl.cloudfront.net/hls/chuctv/master02.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"19","channelName":"Malaysuriactv","videoUrl":"https://d11h6a6nhl9kj9.cloudfront.net/hls/suriactv/master01.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"16","channelName":"Drama Sangat","videoUrl":"https://raw.githubusercontent.com/exodiver/IPTV/master/M3U8/Token/DramaSangat.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"44","channelName":"马来西亚AstroRIA娱乐综合频道","videoUrl":"http://edge.linknetott.swiftserve.com/live/BsNew/amlst:bsworld/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"3","channelName":"Astro Go Shop","videoUrl":"https://agplayback03.aotg-video.astro.com.my/CH2/master_GOSHOP2.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"5","channelName":"Astro Naura","videoUrl":"https://agplayback03.aotg-video.astro.com.my/CH2/master_NAURAGOSHOP4.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"1","channelName":"Astro Awani","videoUrl":"https://bcsecurelivehls-i.akamaihd.net/hls/live/722763/4508222217001/stream04/streamPlaylist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"2","channelName":"Astro Go Shop","videoUrl":"https://agplayback03.aotg-video.astro.com.my/CH1/master_GOSHOP.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"21","channelName":"MetroTV","videoUrl":"http://edge.metrotvnews.com:1935/live-edge/smil:metro.smil/playlist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"4","channelName":"Astro Go Shop Malaya","videoUrl":"https://agplayback03.aotg-video.astro.com.my/CH3/master_GOSHOP3.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"41","channelName":"மக்கள் தொலைக்காட்சி","videoUrl":"https://5k8q87azdy4v-hls-live.wmncdn.net/MAKKAL/271ddf829afeece44d8732757fba1a66.sdp/mono.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"79","channelName":"RTB Sukmaindera","videoUrl":"https://rtb-channel.glue.live/smil:rtb1/chunklist.m3u8"},
{"groupId":"0","groupName":"马新","groupLogo":"无","channelId":"6","channelName":"AstroAwani","videoUrl":"https://bcsecurelivehls-i.akamaihd.net/hls/live/722763/4508222217001/master.m3u8"}
]